Allow overriding Fluent functions
jrmajor/fluent-php pull request #14
Opened 2023-06-06 08:31 UTC by hakastein

Original fluent does not limit function overriding

1. Function overriding allowed
2. FluentBundle no more final

This is especially significant due to the lack of a built-in DATETIME function.

2023-06-07 02:27 UTC, hakastein commented
So, what are you thinking about this request? In the original implementation, there were no limits (https://github.com/projectfluent/fluent.js/blob/main/fluent-bundle/src/bundle.ts#LL75C20-L75C20), and we successfully overwrote built-in functions to support square/cubic units and some messy formats like usd-per-square-meter to support $1000/m².

2023-06-19 04:25 UTC, hakastein commented
Hello, do you plan accept this? Or do you have any questions?

2023-06-19 15:13 UTC, hakastein commented
So all this is necessary for uniform behavior. To make the backend implementation behave the same as the frontend implementation

2023-06-19 20:49 UTC, jrmajor requested changes
Fair enough, we can allow it for the sake of compatibility with `fluent.js`.

Please adjust your changes to the comments I've left and I will merge it.

2023-06-19 20:49 UTC, jrmajor commented on src/Bundle/FluentBundle.php
> +class FluentBundle
Please don't do that, that's not necessary for function overriding.

2023-06-19 20:49 UTC, jrmajor commented on src/Bundle/FluentBundle.php
> -        }
Please follow the pattern from `addResource()` and `addFtl()`.

2023-06-30 11:42 UTC, hakastein commented
Done

2023-07-08 12:20 UTC, jrmajor approved these changes

2023-07-08 12:21 UTC, merged

2023-07-08 12:23 UTC, jrmajor commented
@hakastein Thank you, and sorry for the delay. I will try to release a new version soon :)